columnas = [
    {
        'nombre': 'id',
        'tipo': 'INT',
        'longitud': 11,
        'primary_key': True,
        'auto_increment': True,
        'null': False,
    },
    {
        'nombre': 'nombre',
        'tipo': 'VARCHAR',
        'longitud': 32,
        'primary_key': False,
        'auto_increment': False, 
        'null': False,
    },
    {
        'nombre': 'apellido',
        'tipo': 'VARCHAR',
        'longitud': 64,
        'primary_key': False,
        'auto_increment': False,
        'null': False,
    },
    {
        'nombre': 'telefono',
        'tipo': 'VARCHAR',
        'longitud': 16,
        'primary_key': False,
        'auto_increment': False,
        'null': False,
    },
    {
        'nombre': 'direccion',
        'tipo': 'VARCHAR',
        'longitud': 128,
        'primary_key': False,
        'auto_increment': False,
        'null': False,
    },
    {
        'nombre': 'correo',
        'tipo': 'VARCHAR',
        'longitud': 64,
        'primary_key': False,
        'auto_increment': False,
        'null': False,
    },
]
